/*
    Basic example of unsing SFML
    To compile:
        g++ simple_test.cpp -o simple -lsfml-graphics -lsfml-window -lsfml-system -std=c++11 -g
*/

#include <iostream>
#include <SFML/Graphics.hpp>

int main()
{
	// Create the window
	sf::RenderWindow window(sf::VideoMode(800, 600), "Test application");

	// Create drawable elements
	sf::Texture icon;
	sf::Sprite sprite;
	sf::Font font;
	sf::Text text;

    // Create two concentric circles as a way to have a border
	sf::CircleShape shape(100.f);
	shape.setFillColor(sf::Color::Green);
    // Second circle is larger, and should be drawn first
	sf::CircleShape ring(120.f);
	ring.setFillColor(sf::Color::Yellow);
	// Position the circles
	shape.setOrigin(shape.getRadius(), shape.getRadius());
	shape.setPosition(sf::Vector2f(400, 300));
	ring.setOrigin(ring.getRadius(), ring.getRadius());
	ring.setPosition(sf::Vector2f(400, 300));

    // Create a circle that uses a border parameter
	sf::CircleShape node_shape(100.f, 16);
	node_shape.setFillColor(sf::Color::Red);
	node_shape.setOutlineThickness(20.f);
	node_shape.setOutlineColor(sf::Color::Black);
	node_shape.setOrigin(shape.getRadius(), shape.getRadius());
	node_shape.setPosition(sf::Vector2f(200, 200));

	// Load the image
	if (!icon.loadFromFile("SpaceMegaforce_Icon.png"))
	{
		std::cout << "Could not load image!\n" << std::endl;
	}
	// Load the font
	if (!font.loadFromFile("Akashi.ttf"))
	//if (!font.loadFromFile("heavy_data.ttf"))
	//if (!font.loadFromFile("arial.ttf"))
	{
		std::cout << "Could not load font!\n" << std::endl;
	}

    // Configure the sprite
	sprite.setTexture(icon);
	// Set the center of the sprite to the center of the image
	sprite.setOrigin(icon.getSize().x/2, icon.getSize().y/2);
	// Position the sprite
	sprite.setPosition(sf::Vector2f(400, 300));

	// Configure the text object
	text.setFont(font);
	text.setString("Node 234");
	text.setCharacterSize(24);
	text.setColor(sf::Color::Blue);
    text.setPosition(sf::Vector2f(200, 200));

	while (window.isOpen())
	{
		sf::Event event;
        // Wait for events generated by the window
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();
		}

        // Clean the previous frame
		window.clear(sf::Color::White);

        // Draw the ring first, then the circle
		window.draw(ring);
		window.draw(shape);
        // Using a sprite
		window.draw(sprite);

        // Draw the circle with a border parameter
		window.draw(node_shape);
        // Draw the text
		window.draw(text);

        // Show all elements on the window
		window.display();
	}

	return 0;
}
